### PR TITLE
Search note by title

### LINKED ISSUE #7: Users should be able to search their own notes

### PR DESCRIPTION
**Pull request by jw0711qt**
@mn4774jm , @htietze @xm6264jz @KJTempas 
# The users can search their notes by title

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
@jw0711qt   Good start on the search function!  The basic functionality is there. I've got a few suggestions to make the code cleaner
*In the template note_list.html there is All notes (line 21)  followed by Latest notes (line 30) . I think we probably don't need the 'All notes' tag.  In addition,  line 10 maybe should read 'button type' instead of input type(not real sure about that, but that's what clara often has
*in forms.py, I see your new form.  My only suggest there would be to use search_term instead of search_name.  In the form for venue and artist, you are actually searching for the name of an artist or venue, but here it is just a term
*in view_notes.py - I'd suggest reviewing the video_collection/views.py.   Your requests.GET doesn't look quite right, and you are not checking for form validation. Here also, change to search_term.  I also notice you changed the return to sorting by name, but I think the intent is to order by posted date
*and VERY important - you need some test.  You could likely look at clara's video app tests for guidance. Let me know if you have questions or want to go over any of this

**Comment by xm6264jz** [comment]
@jw0711qt I would suggest that it is better to search by post  date instead title

**Comment by ghost** [comment]
I'm not sure about searching by date, as notes are displayed by date. I
think letting the user search by a search term they enter would be more
useful. We can discuss with the rest of the team in class tonight.  I'm
confused about who's on this issue. I thought it was Filmon.  Are both
Filmon and Ahmed working on it?
Kathryn

**Review by ghost — APPROVED** [review]
Looks great!  good work

**Pull request merged**
